query Articles ($slug:String) {
  articles ( where: { categories : { slug:$slug } } ) {
    id
    slug
    title
    excerpt
    content
    tags
      categories {
        name
      }
    parent {
      slug
      title
    }
    image {
      url
    }
    user {
      firstname
      lastname
    }
  }
}