query Articles {
  articles {
    slug
    title
    excerpt
    content
    homepage
    random_image
    tags
    image {
      url
      caption
      alternativeText
    }
    gallery {
      url
      caption
      alternativeText
    }
    image_title
    updated_at
    SEO {
        description
        title
    }
    categories {
        name
        slug
    }
    parent {
      slug
      title
    }
    template {
      id
      name
    }
  } 
}
