query Category($id: ID!){
  category(id: $id) {
    name
    articles {
      id
      slug
      title
      content
      tags
      lang
      parent {
        slug
        title
      }
      image {
        url
        caption
        alternativeText
      }
      gallery {
        url
        caption
        alternativeText
      }
      categories {
        id
        name
      }
      user {
        firstname
        lastname
        email
      }
    }
  }
}