query Articles {
  articles ( where :{ homepage: true }) {
    title
    content
    excerpt
    homepage
    template_id
    
    lang
    parent {
      title
      slug
    }
    SEO {
      title
      description
    }
  }
}