query Articles ( $tag: String ) {
  articles ( where:{ tags_contains : $tag } ){
    title
    slug
    tags
    lang
    excerpt
    image {
      url
      caption
      alternativeText
    }
    gallery {
      url
      caption
      alternativeText
    }
    user {
      firstname
      lastname
    }
  }
}