query Articles {
  articles ( where :{ homepage: true }) {
    title
    content
    excerpt
    homepage
    component {
      id
      json
    }
    lang
    parent {
      title
      slug
    }
    SEO {
      title
      description
    }
  }
}