query Components {
	components( where : {loop: true}){
    	id
        name
        description
        category
        image {
            url
        }
    	json
        updated_at
    	loop
    	loop_type
        loop_limit
  }
}